{-# OPTIONS_GHC -fno-warn-incomplete-patterns #-}
module FeatureModel.Parsers.FeatureIDE.PrintFeatureIDE where

-- pretty-printer generated by the BNF converter

import FeatureModel.Parsers.FeatureIDE.AbsFeatureIDE
import Data.Char


-- the top-level printing method
printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 (map ($ "") $ d []) "" where
  rend i ss = case ss of
    "["      :ts -> showChar '[' . rend i ts
    "("      :ts -> showChar '(' . rend i ts
    "{"      :ts -> showChar '{' . new (i+1) . rend (i+1) ts
    "}" : ";":ts -> new (i-1) . space "}" . showChar ';' . new (i-1) . rend (i-1) ts
    "}"      :ts -> new (i-1) . showChar '}' . new (i-1) . rend (i-1) ts
    ";"      :ts -> showChar ';' . new i . rend i ts
    t  : "," :ts -> showString t . space "," . rend i ts
    t  : ")" :ts -> showString t . showChar ')' . rend i ts
    t  : "]" :ts -> showString t . showChar ']' . rend i ts
    t        :ts -> space t . rend i ts
    _            -> id
  new i   = showChar '\n' . replicateS (2*i) (showChar ' ') . dropWhile isSpace
  space t = showString t . (\s -> if null s then "" else (' ':s))

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- the printer class does the job
class Print a where
  prt :: Int -> a -> Doc
  prtList :: [a] -> Doc
  prtList = concatD . map (prt 0)

instance Print a => Print [a] where
  prt _ = prtList

instance Print Char where
  prt _ s = doc (showChar '\'' . mkEsc '\'' s . showChar '\'')
  prtList s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q s = case s of
  _ | s == q -> showChar '\\' . showChar s
  '\\'-> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  _ -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j<i then parenth else id


instance Print Integer where
  prt _ x = doc (shows x)


instance Print Double where
  prt _ x = doc (shows x)




instance Print FeatureModel where
  prt i e = case e of
   FeatureModel header featuretree tail -> prPrec i 0 (concatD [prt 0 header , prt 0 featuretree , prt 0 tail])


instance Print Header where
  prt i e = case e of
   Header  -> prPrec i 0 (concatD [doc (showString "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>") , doc (showString "<featureModel chosenLayoutAlgorithm=\"1\">")])


instance Print FeatureTree where
  prt i e = case e of
   FeatureTree feature -> prPrec i 0 (concatD [doc (showString "<struct>") , prt 0 feature , doc (showString "</struct>")])


instance Print Feature where
  prt i e = case e of
   Feature abstractfield mandatoryfield str -> prPrec i 0 (concatD [doc (showString "<feature") , prt 0 abstractfield , prt 0 mandatoryfield , doc (showString "name") , doc (showString "=") , prt 0 str , doc (showString "/>")])
   AndFeature abstractfield mandatoryfield str features -> prPrec i 0 (concatD [doc (showString "<and") , prt 0 abstractfield , prt 0 mandatoryfield , doc (showString "name") , doc (showString "=") , prt 0 str , doc (showString ">") , prt 0 features , doc (showString "</and>")])
   AltFeature abstractfield mandatoryfield str features -> prPrec i 0 (concatD [doc (showString "<alt") , prt 0 abstractfield , prt 0 mandatoryfield , doc (showString "name") , doc (showString "=") , prt 0 str , doc (showString ">") , prt 0 features , doc (showString "</alt>")])
   OrFeature abstractfield mandatoryfield str features -> prPrec i 0 (concatD [doc (showString "<or") , prt 0 abstractfield , prt 0 mandatoryfield , doc (showString "name") , doc (showString "=") , prt 0 str , doc (showString ">") , prt 0 features , doc (showString "</or>")])

  prtList es = case es of
   [] -> (concatD [])
   x:xs -> (concatD [prt 0 x , prt 0 xs])

instance Print AbstractField where
  prt i e = case e of
   AbstractField booleanvalue -> prPrec i 0 (concatD [doc (showString "abstract") , doc (showString "=") , prt 0 booleanvalue])
   NoAbstractFiel  -> prPrec i 0 (concatD [])


instance Print MandatoryField where
  prt i e = case e of
   MandatoryField booleanvalue -> prPrec i 0 (concatD [doc (showString "mandatory") , doc (showString "=") , prt 0 booleanvalue])
   NoMandatoryField  -> prPrec i 0 (concatD [])


instance Print BooleanValue where
  prt i e = case e of
   TrueValue  -> prPrec i 0 (concatD [doc (showString "\"true\"")])
   FalseValue  -> prPrec i 0 (concatD [doc (showString "\"false\"")])


instance Print Tail where
  prt i e = case e of
   Tail  -> prPrec i 0 (concatD [doc (showString "<calculations Auto=\"true\" Constraints=\"true\" Features=\"true\" Redundant=\"true\"/>") , doc (showString "<comments/>") , doc (showString "<featureOrder userDefined=\"false\"/>") , doc (showString "</featureModel>")])



