{-# OPTIONS_GHC -fno-warn-incomplete-patterns #-}
module SPL.Parsers.PrintCK where

-- pretty-printer generated by the BNF converter

import SPL.Parsers.AbsCK
import Data.Char


-- the top-level printing method
printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 (map ($ "") $ d []) "" where
  rend i ss = case ss of
    "["      :ts -> showChar '[' . rend i ts
    "("      :ts -> showChar '(' . rend i ts
    "{"      :ts -> showChar '{' . new (i+1) . rend (i+1) ts
    "}" : ";":ts -> new (i-1) . space "}" . showChar ';' . new (i-1) . rend (i-1) ts
    "}"      :ts -> new (i-1) . showChar '}' . new (i-1) . rend (i-1) ts
    ";"      :ts -> showChar ';' . new i . rend i ts
    t  : "," :ts -> showString t . space "," . rend i ts
    t  : ")" :ts -> showString t . showChar ')' . rend i ts
    t  : "]" :ts -> showString t . showChar ']' . rend i ts
    t        :ts -> space t . rend i ts
    _            -> id
  new i   = showChar '\n' . replicateS (2*i) (showChar ' ') . dropWhile isSpace
  space t = showString t . (\s -> if null s then "" else (' ':s))

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- the printer class does the job
class Print a where
  prt :: Int -> a -> Doc
  prtList :: [a] -> Doc
  prtList = concatD . map (prt 0)

instance Print a => Print [a] where
  prt _ = prtList

instance Print Char where
  prt _ s = doc (showChar '\'' . mkEsc '\'' s . showChar '\'')
  prtList s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q s = case s of
  _ | s == q -> showChar '\\' . showChar s
  '\\'-> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  _ -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j<i then parenth else id


instance Print Integer where
  prt _ x = doc (shows x)


instance Print Double where
  prt _ x = doc (shows x)


instance Print Ident where
  prt _ (Ident i) = doc (showString ( i))



instance Print ConfigurationKnowledge where
  prt i e = case e of
   TConfigurationKnowledge configurationitems -> prPrec i 0 (concatD [doc (showString "configuration knowledge") , doc (showString "{") , prt 0 configurationitems , doc (showString "}")])


instance Print ConfigurationItem where
  prt i e = case e of
   TBasicConfigurationItem featureexp transformations -> prPrec i 0 (concatD [doc (showString "(") , prt 0 featureexp , doc (showString ",") , prt 0 transformations , doc (showString ")")])
   TConstrainedConfigurationItem featureexp0 transformations featureexp1 featureexp -> prPrec i 0 (concatD [doc (showString "(") , prt 0 featureexp0 , doc (showString ",") , prt 0 transformations , doc (showString ",") , prt 0 featureexp1 , doc (showString ",") , prt 0 featureexp , doc (showString ")")])

  prtList es = case es of
   [] -> (concatD [])
   [x] -> (concatD [prt 0 x])
   x:xs -> (concatD [prt 0 x , doc (showString ";") , prt 0 xs])

instance Print Transformation where
  prt i e = case e of
   TSelectScenario ids -> prPrec i 0 (concatD [doc (showString "selectScenario") , doc (showString "(") , prt 0 ids , doc (showString ")")])
   TEvaluateAdvice ids -> prPrec i 0 (concatD [doc (showString "evaluateAdvice") , doc (showString "(") , prt 0 ids , doc (showString ")")])
   TBindParameter id0 id -> prPrec i 0 (concatD [doc (showString "bindParameter") , doc (showString "(") , prt 0 id0 , doc (showString ",") , prt 0 id , doc (showString ")")])
   TSelectComponents ids -> prPrec i 0 (concatD [doc (showString "selectComponents") , doc (showString "(") , prt 0 ids , doc (showString ")")])
   TSelectAndMoveComponent id0 id -> prPrec i 0 (concatD [doc (showString "selectAndMoveComponent") , doc (showString "(") , prt 0 id0 , doc (showString ",") , prt 0 id , doc (showString ")")])
   TSelectBuildEntries ids -> prPrec i 0 (concatD [doc (showString "selectBuildEntries") , doc (showString "(") , prt 0 ids , doc (showString ")")])

  prtList es = case es of
   [] -> (concatD [])
   [x] -> (concatD [prt 0 x])
   x:xs -> (concatD [prt 0 x , doc (showString ",") , prt 0 xs])

instance Print Id where
  prt i e = case e of
   TId id -> prPrec i 0 (concatD [prt 0 id])

  prtList es = case es of
   [] -> (concatD [])
   [x] -> (concatD [prt 0 x])
   x:xs -> (concatD [prt 0 x , doc (showString ",") , prt 0 xs])

instance Print FeatureExp where
  prt i e = case e of
   TBasicExp id -> prPrec i 0 (concatD [prt 0 id])
   TAndExp featureexp0 featureexp -> prPrec i 0 (concatD [doc (showString "And") , doc (showString "(") , prt 0 featureexp0 , doc (showString ",") , prt 0 featureexp , doc (showString ")")])
   TOrExp featureexp0 featureexp -> prPrec i 0 (concatD [doc (showString "Or") , doc (showString "(") , prt 0 featureexp0 , doc (showString ",") , prt 0 featureexp , doc (showString ")")])
   TNotExp featureexp -> prPrec i 0 (concatD [doc (showString "Not") , doc (showString "(") , prt 0 featureexp , doc (showString ")")])



